"""empty message

Revision ID: 431b59aa1d11
Revises: ed7f0a6e6711
Create Date: 2022-06-21 14:41:34.722775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431b59aa1d11'
down_revision = 'ed7f0a6e6711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('memo', 'sent', nullable=True,server_default=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
